remote_theme: DAK404/minimal
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - ./Documentation/Readme.md
  - ./Documentation/License.md
  - ./Documentation/DocumentationIndex.md
  - ./Documentation/Changelog.md

theme: jekyll-theme-minimal
logo: ./assets/Images/Logo.png
title: Nion Truncheon | DAK
description: Official website for Truncheon!
show_downloads: true

github:
  release_url: https://github.com/DAK404/Truncheon/releases/latest/download/Truncheon.zip
  jre_url: https://github.com/DAK404/Truncheon/releases/tag/JRE
  doc_url: https://dak404.github.io/Truncheon/Documentation/index.html