plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - Readme.md
  - License.md
  - Index.md
  - ./Documentation/Program_Documentation/*.html

theme: jekyll-theme-minimal
logo: ./assets/Images/Logo.png
title: Truncheon | DAK
description: Official website for Truncheon!
